# Generated by Django 3.0.7 on 2023-03-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
    ]
